package jhg.amlan;

/**
 * Pronoun
 * @author jgagon
 *
 */
public enum P {
	I(A.THIS,Z.PERSON),
	YOU(A.THAT,Z.PERSON),
	XE(A.OTHER,Z.PERSON),
	WHO(A.WHAT,Z.PERSON),
	ANYONE(A.ANY,Z.PERSON),
	EVERYONE(A.ALL,Z.PERSON),
	NO_ONE(A.NONE,Z.PERSON),
	SOMEONE(A.SOME,Z.PERSON),
	PERSON(A.NULL,Z.PERSON),
	WE(A.THIS,Z.PEOPLE),
	YOUALL(A.THAT,Z.PEOPLE),
	THEY(A.OTHER,Z.PEOPLE),
	
	MY(A.THIS,Z.PERSONS),
	OUR(A.THIS,Z.PEOPLES),
	MINE(A.THIS,Z.PERSONSTHING),
	OURS(A.THIS,Z.PEOPLESTHING),
	MYSELF(A.THIS,Z.SELF),
	OURSELVES(A.THIS,Z.SELVES),
	THIS(A.THIS,Z.THING),
	THESE(A.THIS,Z.THINGS),
	THISIDEA(A.THIS,Z.IDEA),
	THISACT(A.THIS,Z.ACT),
	NOW(A.THIS,Z.TIME),
	HERE(A.THIS,Z.PLACE),
	WHICHOFTHESE(A.THIS,Z.GROUP),
	THISWAY(A.THIS,Z.WAY),
	THISREASON(A.THIS,Z.REASON)
	
	/*
	*/
	;
	
	private P(A a, Z z){
		
	}
}
/*
 * 

 * 
*/
